# Generated by Django 2.1.4 on 2018-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='authors',
            field=models.CharField(max_length=250),
        ),
    ]
