# Generated by Django 2.1.5 on 2019-01-11 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0006_auto_20190107_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisees', to=settings.AUTH_USER_MODEL),
        ),
    ]
