# Generated by Django 2.1.5 on 2019-01-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_thesis_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
